name: ltogt_utils
description: A collection of utility classes, functions, extensions, helpers, ...
version: 0.0.2
homepage: https://github.com/ltOgt

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:

flutter: null
