name: ltogt_utils
description: A collection of utility classes, functions, extensions, helpers, ...
version: 0.0.4
homepage: https://github.com/ltOgt

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.2

dev_dependencies:
  test:

flutter: null
