name: ltogt_utils
description: A collection of utility classes, functions, extensions, helpers, ...
version: 0.0.3
homepage: https://github.com/ltOgt

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  path: 1.8.0

dev_dependencies:
  test:

flutter: null
